### ISSUE TITLE
next batch of articles

### ISSUE THREAD

**Issue by afknapping** [DesignOps/designops.github.io#18]
- [ ] [Succeeding in mobile DevOps - TechWorld](https://www.techworld.com.au/article/626950/succeeding-mobile-devops/)

> As the volume of work in enterprise app development increases, IT operations and business owners need to reconsider their approach to DevOps and incorporate DesignOps to effectively bridge the gap in mobile app development.

**Comment by filtercake** [comment]
- [Scoot over DevOps, make room for DesignOps](http://diginomica.com/2017/06/26/scoot-over-devops-make-room-for-designops/)
- [There’s no Design, at Scale, without DesignOps | Michael Polivka | Pulse | LinkedIn](https://www.linkedin.com/pulse/theres-design-scale-without-designops-michael-polivka)
- [DesignOps: Bridging the developer, designer communication gap](http://searchsoftwarequality.techtarget.com/news/450421998/DesignOps-Bridging-the-developer-designer-communication-gap)
- [DevOps for Designers – Hacker Noon](https://hackernoon.com/devops-for-designers-e5080a2be6e4)
- 1st [DesignOps Summit](http://designopssummit.com/), November, New York
- [► Melissa Milloway On Design Ops, XAPI, And A/B Testing - TLDChat (podcast)](https://player.fm/series/tldchat/melissa-milloway-on-design-ops-xapi-and-ab-testing)

**Comment by filtercake** [comment]
[DesignOps in a Post-Industrial World: Crash-Coursing Complex Systems with Jeff Sussna by Rosenfeld Media | Free Listening on SoundCloud](https://soundcloud.com/rosenfeld-media/jeff-sussna-podcast)

**Comment by filtercake** [comment]
[Design Ops — A New Discipline | Clearleft](https://clearleft.com/posts/491)

**Comment by filtercake** [comment]
[DesignOps: Unleashing the potential of our design studio - Atlassian Blog](https://www.atlassian.com/blog/inside-atlassian/designops-atlassian-design-studio)

**Comment by filtercake** [comment]
[NEW KID ON THE BLOCK IN DESIGN TACTICS: A short introduction to DesignOps- INFORMAAT experience design](http://informaat.com/blog/new-kid-on-the-block-in-design-tactics.php)
