### ISSUE TITLE
enhancing content management, stack and infrastructure

### ISSUE THREAD

**Issue by afknapping** [DesignOps/designops.github.io#19]
some thoughts in no particular order

- pagination
- rss
- pinned articles in the current picture-heavy card format vs simple list for all the things to keep weight down and perf up
- i did a lot of [jekyll](https://jekyllrb.com/) in the past, which is integrated into gh-pages and would keep things static for now. also, adding links via simple markdown down files is a lower hurdle than understanding the current spaghetti html
- gh pages has no ssl though, moving to gitlab with letsencrypt would be an option. gitlab also offers an integrated travis-like ci for real build steps. that would enable this customisation and some standard tooling in the future (jekyll plugins, all the node-based stuffs etc).
- [Jekyll Admin](https://jekyll.github.io/jekyll-admin/) would be option if we want to run full infrastructure later
- that *might* be a nice migration path: move to jekyll, move to gitlab, move to own server and add jekyll-admin

i expect a lot of content to come after the designops summit, so would like to have the next step done in october. imo the main objective should be to **make adding and categorizing content simpler than it is now** and moving to jekyll would achieve that.

all feedback is welcome...

**Comment by filtercake** [comment]
Content model

Required:

- title
- url
- type: article, video, slides, audio,...

Optional:

- pinned post?
  - poster image url
  - poster license
  - poster creator
- money quote
