### ISSUE TITLE
Companies featuring design ops roles and job offerings

### ISSUE THREAD

**Issue by afknapping** [DesignOps/designops.github.io#22]

**Comment by filtercake** [comment]
Sr. Visual Designer, Design Ops - Job ID: 585640 - Amazon.jobs
https://www.amazon.jobs/en/jobs/585640/sr-visual-designer-design-ops

—-

DESCRIPTION

Amazon Human-Centered Design (HCD) is a multidisciplinary user experience team within Amazon’s Operations organization. We own user experience and design for Customer Service, Fulfillment Systems, Prime Now, AMZL, Last Mile, Locker , and Transportation-related products.

The Role:
As a Senior Visual Designer for the HCD Design Ops team, you will work closely with key stakeholders, development, and senior partners to deliver horizontal internal solutions that support our product design teams. The Senior Visual Designer should have deep knowledge and practical experience in software design, from design concept creation to development and release and possess excellent communication skills.

Responsibilities:
· Develop and champion a holistic point-of-view of the design language that creates the user experience of Human-Centered Design team.
· Create, craft, and evangelize visual design systems and processes that support multiple studio teams of UX Designers and Design Technologists across the Human-Centered Design team.
· Collaborate with design teams outside of Human-Centered Design to bring harmony and familiarity to the multiple experiences presented by Amazon, as they impact the business customer experience.
· Scope design initiatives and manage/prioritize work items across multiple HCD studios.
· Understand and respond to performance data (metric tests, usability studies), and steer the direction of future creative designs.
· Communicate clearly with both internal and external customers.
BASIC QUALIFICATIONS

· An online portfolio demonstrating strong conceptual thinking and creative problem solving.
· 7+ years visual design experience in application / web design.
· Experience designing for web and mobile.
· Experience creating and maintaining design systems.
· Experience managing multiple projects and the ability to meet aggressive deadlines.
· Ability to manage ambiguity, work autonomously, and multi-task.
· Ability to work across organizational boundaries to define, manage, and prioritize work.
· Proficiency with design tools such as Photoshop, Illustrator, Sketch, After Effects, and InDesign.
· Bachelor degree in design or equivalent professional experience required.
PREFERRED QUALIFICATIONS

· Experience presenting to and effectively advising senior management.
· Experience in a customer-centric, insights-driven design environment.
· Experience with agile/scrum.
· An informed set of core values regarding user experience, technology, and business communication and the ability to present them with eloquence and precision.
· Unwavering attention to detail with an acute awareness that everything counts.
· Relentless desire for innovation, balanced with business needs and customer expectations.
· Experience working with a variety of front end development platforms.
· Committed to learning and expanding professional and technical knowledge.
· Background in script writing or creative writing is a plus
