### ISSUE TITLE
improve inital version

### ISSUE THREAD

**Issue by afknapping** [DesignOps/designops.github.io#4]
- [ ] title
- [ ] `<meta name=viewport content="width=device-width, initial-scale=1">`
- [ ] code cleanup
- [ ] document what how why
- [ ] description
- [ ] hover styles
- [ ] preview pulled into slack when sharing the domain
- [ ] cross browser check
- [ ] weight check, image shrinking

**Comment by filtercake** [comment]
some cleanup: #14
