### ISSUE TITLE
list of people to follow/read somewhere

### ISSUE THREAD

**Issue by afknapping** [DesignOps/designops.github.io#5]
@kaelig says in #3:

> I think it'd make sense to add a list of people to follow/read somewhere, a bit like this: https://uptodate.frontendrescue.org/

**Comment by filtercake** [comment]
for me this ties deeply into https://github.com/DesignOps/discussion/issues/3 and https://github.com/DesignOps/discussion/issues/6

there are three dangers here:

a) creating a "club"
b) creating a "cool people club"
c) creating a cis/white/male club

All three would be the opposite of what I want to create and **I assume that is true for everybody involved :)**

Some of my learnings on this topic – some are just *related* and maybe not strictly relevant to the specific idea of a list:

- good intentions are not making sure that no harm is done
- "not doing harm" is not a great goal for community work
- "not feeling privileged" is the very definition of privilege
- privilege brings bias
- [cognitive biases](https://en.wikipedia.org/wiki/List_of_cognitive_biases) are a thing, let's look out for them (so far three white males are the only members of the org)
- community work is real work and it is the most important work, too. everything is about people
- you cannot make things "too open"
- you cannot make things "too inclusive" or "too diverse"
- you cannot be "too early" with diversity/inclusivity efforts
- hurdles for contribution cannot be "too low"
- ownership of contribution is one of the most important things a community can provide
- you cannot over-communicate all of this
- you cannot over-educate all of this

To get back to "list of people to follow/read somewhere":

- I like the idea of a list in the sense of a "community index"
- everybody should be able to add themselves to that list via contributing
- imo an mvp of that list already exists and is located at [github.com/orgs/DesignOps/people](https://github.com/orgs/DesignOps/people) :)
- I would prefer one which collects all people who have contributed to the org in any form (following the model outlined in [Healthy Open Source](https://medium.com/the-javascript-collection/healthy-open-source-967fa8be7951#.rgm2ysc3b): everybody who commented on an issue or even sent a commit is a *contributor*
- I guess the github API should allow to generate a more inviting list (more like the one located at frontendrescue) from the current public org membership
- it should be possible for everybody to join that list
- it should feel safe, welcome and inviting to do so
- before that list exists, we should make sure it would not be perceived as a cis/white/male club by people who are not cis/white/male – and yeah, that probably means reaching out to non-cis/white/male communities. I don't have a plan yet here. but the more we want to gather ideas and the more we want to build a *community* and not a club, the more important outreach becomes (for example see the [idea on a "call for papers"](https://github.com/DesignOps/discussion/issues/1#issuecomment-201179067))
- I'd like to ask people on this topic who have first-hand experience with it, but I don't want to ask them to do the work for us. If we follow that path, we should work out a lean plan and then I hope they will provide feedback
- the public version of the list is currently this :(
  ![image](https://cloud.githubusercontent.com/assets/170145/14042683/99ebba3c-f27c-11e5-9718-1ce28e59f92c.png)


---

I know – a very long answer on an initally simple idea :/  I hope I could express why it is so important to me. We the have the chance here to bake in *diverse* community from the start and I would prefer that very much to a *large* community or worse (like accidentally creating a cool people club). I deeply care about it, I did a lot of research and listening in the past two years and I will gladly focus on that work in the coming months of DesignOps :)

**Comment by kaelig** [comment]
Ouch, you're right… the "cool people club" effect is true. Thank you for bringing this up.

If we make a list we'll need to be very careful about the messaging.
